version: "3.8"

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/bitnami/mariadb

  myapp:
    image: docker.io/bitnami/laravel:9
    ports:
      - "8000:8000"
      - "5173:5173" # Exponer el puerto para Vite
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=bitnami_myapp
    volumes:
      - "./my-project:/app"
    depends_on:
      - mariadb
    working_dir: /app

volumes:
  mariadb_data:
